# Generated by Django 4.2.5 on 2023-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='colorPreference',
            field=models.CharField(max_length=7),
        ),
    ]
