# Generated by Django 4.1.4 on 2023-11-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_userdata_colorpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='colorPreference',
            field=models.CharField(default='#0035fe', max_length=7),
        ),
    ]
