# Generated by Django 4.2.5 on 2023-09-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userdata_delete_friendhubuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='djangoUser',
        ),
    ]
