# Generated by Django 4.2.5 on 2023-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_user_userdata_djangouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='application.userdata'),
        ),
    ]
