# Generated by Django 4.2.5 on 2023-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_userdata_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, to='application.userdata'),
        ),
    ]
