# Generated by Django 4.1.4 on 2023-10-01 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_userdata_pendingfriends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='pendingFriends',
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='application.userdata')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='application.userdata')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
