# Generated by Django 4.1.4 on 2023-10-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_userdata_pendingfriends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
