# Generated by Django 4.1.4 on 2023-10-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_friendrequest_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
    ]
