# Generated by Django 4.1.4 on 2023-10-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
