# Generated by Django 4.1.4 on 2023-10-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_delete_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
