# Generated by Django 4.1.4 on 2023-10-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
