# Generated by Django 4.1.4 on 2023-10-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
