# Generated by Django 4.1.4 on 2023-10-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='isActive',
        ),
    ]
