# Generated by Django 4.1.4 on 2023-10-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_remove_userdata_friends_friendlist_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, to='application.userdata'),
        ),
    ]
