# Generated by Django 4.1.4 on 2023-10-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_userdata_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='distancePreference',
            field=models.IntegerField(default=1),
        ),
    ]
