# Generated by Django 4.2.5 on 2023-10-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_userdata_distancepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='colorPreference',
            field=models.CharField(default='#007bff', max_length=10),
        ),
    ]
