# Generated by Django 4.2.5 on 2023-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_alter_userdata_colorpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='colorPreference',
            field=models.IntegerField(default=1),
        ),
    ]
