# Generated by Django 4.2.5 on 2023-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alter_userdata_colorpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='iconPreference',
            field=models.IntegerField(default=1),
        ),
    ]
