# Generated by Django 4.2.5 on 2023-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_userdata_iconpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='distancePreference',
            field=models.IntegerField(default=6),
        ),
    ]
